// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRZr-K_GMOStmBQoP5brg3F82pUT7Syo',
    appId: '1:148586252950:android:0ab78282368d03cad510b7',
    messagingSenderId: '148586252950',
    projectId: 'fir-auth-1-5605f',
    storageBucket: 'fir-auth-1-5605f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQS4goXv9EQdEqa08EGekyAhBiD66x1z4',
    appId: '1:148586252950:ios:ce4355ef6062d5cbd510b7',
    messagingSenderId: '148586252950',
    projectId: 'fir-auth-1-5605f',
    storageBucket: 'fir-auth-1-5605f.appspot.com',
    iosBundleId: 'com.example.firebaseAuth1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcaOyMuY9l7iCj0-txCKzZJQ7jp08Jfss',
    appId: '1:148586252950:web:6f889718fa2f90ead510b7',
    messagingSenderId: '148586252950',
    projectId: 'fir-auth-1-5605f',
    authDomain: 'fir-auth-1-5605f.firebaseapp.com',
    storageBucket: 'fir-auth-1-5605f.appspot.com',
  );
}
